name: Slack notification

on:
  workflow_call:
    inputs:
      deploy-job-status:
        required: true
        type: string
      env-name:
        required: true
        type: string
      url:
        required: true
        type: string
    secrets:
      slack-webhook-url:
        required: true

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send success message to Slack
        if: ${{ inputs.deploy-job-status == 'success' }}
        id: slack-success
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"Se realizó el despliegue del front-end en el ambiente de *${{ inputs.env-name }}*"}},{"type":"section","text":{"type":"mrkdwn","text":"${{ inputs.url }}"}}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Send failure message to Slack
        if: ${{ inputs.deploy-job-status == 'failure' }}
        id: slack-failure
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"El despliegue del front-end en el ambiente de *${{ inputs.env-name }}* tuvo errores"}}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Send cancelled message to Slack
        if: ${{ inputs.deploy-job-status == 'cancelled' }}
        id: slack-cancelled
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: '{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"El despliegue del front-end en el ambiente de *${{ inputs.env-name }}* fue cancelado"}}]}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

